import Link from 'next/link';
import {
  Search,
  ArrowRight,
  TrendingUp,
  Users,
  Award,
  Eye,
  Hammer,
  GraduationCap,
} from 'lucide-react';
import { createServerSupabase } from '@/lib/supabase/server';
import SolutionCard from '@/components/ui/SolutionCard';
import type { Solution } from '@/types';

export const dynamic = 'force-dynamic';

const HOW_IT_WORKS = [
  {
    icon: Eye,
    title: 'Watch',
    text: 'Browse 7,000+ solutions across 20+ categories and find the ones your neighborhood needs.',
  },
  {
    icon: Hammer,
    title: 'Build',
    text: 'Follow the step-by-step build guide — timeline, budget, and partners included. Track progress on your dashboard.',
  },
  {
    icon: GraduationCap,
    title: 'Teach',
    text: 'Log a teaching session when you show someone else the solution and earn karma for spreading impact.',
  },
];

export default async function HomePage() {
  const supabase = createServerSupabase();
  const { count } = await supabase
    .from('solutions')
    .select('*', { count: 'exact', head: true });

  const total = count ?? 7000;

  const { data: featured } = await supabase
    .from('solutions')
    .select('*')
    .order('created_at', { ascending: false })
    .limit(6);

  const featuredSolutions = (featured as unknown as Solution[]) ?? [];

  return (
    <div>
      {/* Hero */}
      <section className="bg-gradient-to-br from-primary via-teal-700 to-slate-900 text-white">
        <div className="max-w-7xl mx-auto px-4 py-20 md:py-28 text-center">
          <h1 className="text-4xl md:text-6xl font-bold mb-6">
            {total.toLocaleString()} AI-Powered Solutions to World Issues
          </h1>
          <p className="text-lg md:text-xl text-teal-100 max-w-3xl mx-auto mb-8">
            Explore 7,000+ actionable solutions across 20+ categories — each one
            generated by AI, ranked by impact, with a step-by-step build guide, and
            ready to be built in your city.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              href="/browse"
              className="inline-flex items-center justify-center gap-2 bg-white text-primary px-8 py-4 rounded-xl font-semibold text-lg hover:bg-teal-50 transition-colors shadow-lg"
            >
              <Search className="w-5 h-5" />
              Explore Solutions
            </Link>
            <Link
              href="/whitepaper"
              className="inline-flex items-center justify-center gap-2 border-2 border-white/30 px-8 py-4 rounded-xl font-semibold text-lg hover:bg-white/10 transition-colors"
            >
              Read the Whitepaper
              <ArrowRight className="w-5 h-5" />
            </Link>
          </div>

          <div className="mt-14 flex flex-wrap justify-center gap-4">
            <div className="glass-dark rounded-2xl px-6 py-3 flex items-center gap-3">
              <TrendingUp className="w-5 h-5 text-teal-300" />
              <span className="text-sm text-teal-50">
                <strong className="text-white font-bold">{total.toLocaleString()}</strong> solutions
              </span>
            </div>
            <div className="glass-dark rounded-2xl px-6 py-3 flex items-center gap-3">
              <Users className="w-5 h-5 text-teal-300" />
              <span className="text-sm text-teal-50">
                <strong className="text-white font-bold">20+</strong> categories
              </span>
            </div>
            <div className="glass-dark rounded-2xl px-6 py-3 flex items-center gap-3">
              <Award className="w-5 h-5 text-teal-300" />
              <span className="text-sm text-teal-50">
                Pilot cities <strong className="text-white font-bold">Detroit & St. Louis</strong>
              </span>
            </div>
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="max-w-7xl mx-auto px-4 py-16">
        <h2 className="text-2xl md:text-3xl font-bold mb-2 text-center">
          Watch. Build. Teach.
        </h2>
        <p className="text-slate-500 text-center mb-10">
          The community flywheel that turns solutions into local action.
        </p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {HOW_IT_WORKS.map((step, idx) => (
            <div key={step.title} className="card text-center">
              <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-primary to-secondary text-white flex items-center justify-center mx-auto mb-4 shadow-lg">
                <step.icon className="w-7 h-7" />
              </div>
              <h3 className="font-bold text-xl mb-2">
                {idx + 1}. {step.title}
              </h3>
              <p className="text-sm text-slate-600 leading-relaxed">{step.text}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Stats */}
      <section className="max-w-7xl mx-auto px-4 pb-12 grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="card flex items-center gap-4">
          <TrendingUp className="w-10 h-10 text-primary" />
          <div>
            <p className="text-3xl font-bold">{total.toLocaleString()}</p>
            <p className="text-slate-500">AI-Generated Solutions</p>
          </div>
        </div>
        <div className="card flex items-center gap-4">
          <Users className="w-10 h-10 text-primary" />
          <div>
            <p className="text-3xl font-bold">20+</p>
            <p className="text-slate-500">Categories</p>
          </div>
        </div>
        <div className="card flex items-center gap-4">
          <Award className="w-10 h-10 text-primary" />
          <div>
            <p className="text-3xl font-bold">1,000+</p>
            <p className="text-slate-500">Local Experts</p>
          </div>
        </div>
      </section>

      {/* Featured solutions */}
      {featuredSolutions.length > 0 && (
        <section className="max-w-7xl mx-auto px-4 pb-16">
          <div className="flex items-end justify-between mb-6">
            <h2 className="text-2xl md:text-3xl font-bold">Featured Solutions</h2>
            <Link href="/browse" className="chip">
              View all <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {featuredSolutions.map((solution) => (
              <SolutionCard key={solution.id} solution={solution} />
            ))}
          </div>
        </section>
      )}

      {/* Explore by category */}
      <section className="max-w-7xl mx-auto px-4 pb-16">
        <h2 className="text-2xl md:text-3xl font-bold mb-6">Explore by Category</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {[
            'Education',
            'Healthcare',
            'Public Safety',
            'Environment',
            'Transportation',
            'Economic Development',
            'Housing',
            'Digital Equity',
          ].map((category) => (
            <Link
              key={category}
              href={`/browse?category=${encodeURIComponent(category)}`}
              className="card hover:border-primary transition-colors"
            >
              <h3 className="font-semibold text-lg mb-2">{category}</h3>
              <p className="text-sm text-slate-500">View solutions →</p>
            </Link>
          ))}
        </div>
      </section>
    </div>
  );
}
